/**
 * splitit-web-api-public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SplititWebApiPublic);
  }
}(this, function(expect, SplititWebApiPublic) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SplititWebApiPublic.CardData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CardData', function() {
    it('should create an instance of CardData', function() {
      // uncomment below and update the code to test CardData
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be.a(SplititWebApiPublic.CardData);
    });

    it('should have the property cardId (base name: "CardId")', function() {
      // uncomment below and update the code to test the property cardId
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property cardNumber (base name: "CardNumber")', function() {
      // uncomment below and update the code to test the property cardNumber
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property cardExpMonth (base name: "CardExpMonth")', function() {
      // uncomment below and update the code to test the property cardExpMonth
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property cardExpYear (base name: "CardExpYear")', function() {
      // uncomment below and update the code to test the property cardExpYear
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property cardBrand (base name: "CardBrand")', function() {
      // uncomment below and update the code to test the property cardBrand
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property cardType (base name: "CardType")', function() {
      // uncomment below and update the code to test the property cardType
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property bin (base name: "Bin")', function() {
      // uncomment below and update the code to test the property bin
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property cardHolderFullName (base name: "CardHolderFullName")', function() {
      // uncomment below and update the code to test the property cardHolderFullName
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property cardCvv (base name: "CardCvv")', function() {
      // uncomment below and update the code to test the property cardCvv
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "Address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "Token")', function() {
      // uncomment below and update the code to test the property token
      //var instane = new SplititWebApiPublic.CardData();
      //expect(instance).to.be();
    });

  });

}));
