/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class InstallmentPlanActivityStatus.
* @enum {}
* @readonly
*/
export default class InstallmentPlanActivityStatus {
    
        /**
         * value: "None"
         * @const
         */
        "None" = "None";

    
        /**
         * value: "All"
         * @const
         */
        "All" = "All";

    
        /**
         * value: "Processed"
         * @const
         */
        "Processed" = "Processed";

    
        /**
         * value: "Planned"
         * @const
         */
        "Planned" = "Planned";

    

    /**
    * Returns a <code>InstallmentPlanActivityStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/InstallmentPlanActivityStatus} The enum <code>InstallmentPlanActivityStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

