/**
 * splitit-web-api-public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PurchaseMethod.
* @enum {}
* @readonly
*/
export default class PurchaseMethod {
    
        /**
         * value: "InStore"
         * @const
         */
        "InStore" = "InStore";

    
        /**
         * value: "PhoneOrder"
         * @const
         */
        "PhoneOrder" = "PhoneOrder";

    
        /**
         * value: "ECommerce"
         * @const
         */
        "ECommerce" = "ECommerce";

    

    /**
    * Returns a <code>PurchaseMethod</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PurchaseMethod} The enum <code>PurchaseMethod</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

