/**
 * splitit-web-api-public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReferenceEntityBase from './ReferenceEntityBase';

/**
 * The TransactionResult model module.
 * @module model/TransactionResult
 * @version 1.0.0
 */
class TransactionResult {
    /**
     * Constructs a new <code>TransactionResult</code>.
     * @alias module:model/TransactionResult
     * @param gatewayResult {Boolean} 
     * @param gatewayTransactionDate {Date} 
     */
    constructor(gatewayResult, gatewayTransactionDate) { 
        
        TransactionResult.initialize(this, gatewayResult, gatewayTransactionDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gatewayResult, gatewayTransactionDate) { 
        obj['GatewayResult'] = gatewayResult;
        obj['GatewayTransactionDate'] = gatewayTransactionDate;
    }

    /**
     * Constructs a <code>TransactionResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionResult} obj Optional instance to populate.
     * @return {module:model/TransactionResult} The populated <code>TransactionResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionResult();

            if (data.hasOwnProperty('GatewayTransactionId')) {
                obj['GatewayTransactionId'] = ApiClient.convertToType(data['GatewayTransactionId'], 'String');
            }
            if (data.hasOwnProperty('GatewayResultCode')) {
                obj['GatewayResultCode'] = ApiClient.convertToType(data['GatewayResultCode'], 'String');
            }
            if (data.hasOwnProperty('GatewayResultMessage')) {
                obj['GatewayResultMessage'] = ApiClient.convertToType(data['GatewayResultMessage'], 'String');
            }
            if (data.hasOwnProperty('OperationType')) {
                obj['OperationType'] = ReferenceEntityBase.constructFromObject(data['OperationType']);
            }
            if (data.hasOwnProperty('GatewayResult')) {
                obj['GatewayResult'] = ApiClient.convertToType(data['GatewayResult'], 'Boolean');
            }
            if (data.hasOwnProperty('GatewayTransactionDate')) {
                obj['GatewayTransactionDate'] = ApiClient.convertToType(data['GatewayTransactionDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} GatewayTransactionId
 */
TransactionResult.prototype['GatewayTransactionId'] = undefined;

/**
 * @member {String} GatewayResultCode
 */
TransactionResult.prototype['GatewayResultCode'] = undefined;

/**
 * @member {String} GatewayResultMessage
 */
TransactionResult.prototype['GatewayResultMessage'] = undefined;

/**
 * @member {module:model/ReferenceEntityBase} OperationType
 */
TransactionResult.prototype['OperationType'] = undefined;

/**
 * @member {Boolean} GatewayResult
 */
TransactionResult.prototype['GatewayResult'] = undefined;

/**
 * @member {Date} GatewayTransactionDate
 */
TransactionResult.prototype['GatewayTransactionDate'] = undefined;






export default TransactionResult;

