/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseHeader from './ResponseHeader';

/**
 * The VerifyPaymentResponse model module.
 * @module model/VerifyPaymentResponse
 * @version 1.3.5
 */
class VerifyPaymentResponse {
    /**
     * Constructs a new <code>VerifyPaymentResponse</code>.
     * @alias module:model/VerifyPaymentResponse
     * @param isPaid {Boolean} 
     */
    constructor(isPaid) { 
        
        VerifyPaymentResponse.initialize(this, isPaid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isPaid) { 
        obj['IsPaid'] = isPaid;
    }

    /**
     * Constructs a <code>VerifyPaymentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VerifyPaymentResponse} obj Optional instance to populate.
     * @return {module:model/VerifyPaymentResponse} The populated <code>VerifyPaymentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VerifyPaymentResponse();

            if (data.hasOwnProperty('ResponseHeader')) {
                obj['ResponseHeader'] = ResponseHeader.constructFromObject(data['ResponseHeader']);
            }
            if (data.hasOwnProperty('IsPaid')) {
                obj['IsPaid'] = ApiClient.convertToType(data['IsPaid'], 'Boolean');
            }
            if (data.hasOwnProperty('OriginalAmountPaid')) {
                obj['OriginalAmountPaid'] = ApiClient.convertToType(data['OriginalAmountPaid'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ResponseHeader} ResponseHeader
 */
VerifyPaymentResponse.prototype['ResponseHeader'] = undefined;

/**
 * @member {Boolean} IsPaid
 */
VerifyPaymentResponse.prototype['IsPaid'] = undefined;

/**
 * @member {Number} OriginalAmountPaid
 */
VerifyPaymentResponse.prototype['OriginalAmountPaid'] = undefined;






export default VerifyPaymentResponse;

