/* 
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Splitit.SDK.Client.Client.SwaggerDateConverter;

namespace Splitit.SDK.Client.Model
{
    /// <summary>
    /// Defines CardBrand
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum CardBrand
    {
        
        /// <summary>
        /// Enum Mastercard for value: Mastercard
        /// </summary>
        [EnumMember(Value = "Mastercard")]
        Mastercard = 1,
        
        /// <summary>
        /// Enum Visa for value: Visa
        /// </summary>
        [EnumMember(Value = "Visa")]
        Visa = 2,
        
        /// <summary>
        /// Enum AmericanExpress for value: AmericanExpress
        /// </summary>
        [EnumMember(Value = "AmericanExpress")]
        AmericanExpress = 3,
        
        /// <summary>
        /// Enum Maestro for value: Maestro
        /// </summary>
        [EnumMember(Value = "Maestro")]
        Maestro = 4,
        
        /// <summary>
        /// Enum JCB for value: JCB
        /// </summary>
        [EnumMember(Value = "JCB")]
        JCB = 5,
        
        /// <summary>
        /// Enum CUP for value: CUP
        /// </summary>
        [EnumMember(Value = "CUP")]
        CUP = 6,
        
        /// <summary>
        /// Enum UPI for value: UPI
        /// </summary>
        [EnumMember(Value = "UPI")]
        UPI = 7,
        
        /// <summary>
        /// Enum Discover for value: Discover
        /// </summary>
        [EnumMember(Value = "Discover")]
        Discover = 8,
        
        /// <summary>
        /// Enum Other for value: Other
        /// </summary>
        [EnumMember(Value = "Other")]
        Other = 9
    }

}
