/*
 * splitit-web-api-public-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.splitit.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.splitit.sdk.model.AccountUpdaterPendingCards;
import com.splitit.sdk.model.AddressData2;
import com.splitit.sdk.model.BinData;
import com.splitit.sdk.model.CardBrand;
import com.splitit.sdk.model.CardStateLogs;
import com.splitit.sdk.model.CardType;
import com.splitit.sdk.model.Countries;
import com.splitit.sdk.model.CountrySubdivisions;
import com.splitit.sdk.model.DEKData;
import com.splitit.sdk.model.EntityBase;
import com.splitit.sdk.model.FraudDetectionLogs;
import com.splitit.sdk.model.InstallmentPlanAuditLogs;
import com.splitit.sdk.model.InstallmentPlans;
import com.splitit.sdk.model.Keks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Cards
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-06T07:48:08.244Z")
public class Cards  {
  @SerializedName("Id")
  private Long id = null;

  @SerializedName("KekId")
  private Long kekId = null;

  @SerializedName("BinBinNumber")
  private String binBinNumber = null;

  @SerializedName("BinIssuingCountryIsoNumber")
  private String binIssuingCountryIsoNumber = null;

  @SerializedName("BinId")
  private Long binId = null;

  @SerializedName("ExpirationMonth")
  private Integer expirationMonth = null;

  @SerializedName("ExpirationYear")
  private Integer expirationYear = null;

  @SerializedName("AddressDataAddressLine")
  private String addressDataAddressLine = null;

  @SerializedName("AddressDataZip")
  private String addressDataZip = null;

  @SerializedName("IsDeleted")
  private Boolean isDeleted = null;

  @SerializedName("Version")
  private Integer version = null;

  @SerializedName("PisMemberUniqueId")
  private String pisMemberUniqueId = null;

  @SerializedName("PisMemberId")
  private Long pisMemberId = null;

  @SerializedName("AddressDataAddressLine2")
  private String addressDataAddressLine2 = null;

  @SerializedName("AddressDataCity")
  private String addressDataCity = null;

  @SerializedName("AddressDataCountryId")
  private Long addressDataCountryId = null;

  @SerializedName("AddressDataStateId")
  private Long addressDataStateId = null;

  @SerializedName("AddressDataLegacyFullAddressLine")
  private String addressDataLegacyFullAddressLine = null;

  @SerializedName("BinIsPrepaid")
  private Boolean binIsPrepaid = null;

  @SerializedName("Token")
  private String token = null;

  @SerializedName("Kek")
  private Keks kek = null;

  @SerializedName("CardClass")
  private String cardClass = null;

  @SerializedName("ProductId")
  private String productId = null;

  @SerializedName("IssuerBankName")
  private String issuerBankName = null;

  @SerializedName("DekDataId")
  private Long dekDataId = null;

  @SerializedName("DekData")
  private DEKData dekData = null;

  @SerializedName("PisMember")
  private Object pisMember = null;

  @SerializedName("AccountUpdaterPendingCards")
  private List<AccountUpdaterPendingCards> accountUpdaterPendingCards = null;

  @SerializedName("CardStateLogs")
  private List<CardStateLogs> cardStateLogs = null;

  @SerializedName("FraudDetectionLogs")
  private List<FraudDetectionLogs> fraudDetectionLogs = null;

  @SerializedName("InstallmentPlanAuditLogs")
  private List<InstallmentPlanAuditLogs> installmentPlanAuditLogs = null;

  @SerializedName("InstallmentPlans")
  private List<InstallmentPlans> installmentPlans = null;

  @SerializedName("AddressData")
  private AddressData2 addressData = null;

  @SerializedName("EncryptedNumber")
  private String encryptedNumber = null;

  @SerializedName("Dek")
  private String dek = null;

  @SerializedName("MaskedNumber")
  private String maskedNumber = null;

  @SerializedName("CardHolderName")
  private String cardHolderName = null;

  @SerializedName("BinCardBrand")
  private CardBrand binCardBrand = null;

  @SerializedName("BinCardType")
  private CardType binCardType = null;

  @SerializedName("Cvv")
  private String cvv = null;

  @SerializedName("Bin")
  private BinData bin = null;

  @SerializedName("Country")
  private Countries country = null;

  @SerializedName("State")
  private CountrySubdivisions state = null;

  public Cards id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Cards kekId(Long kekId) {
    this.kekId = kekId;
    return this;
  }

   /**
   * Get kekId
   * @return kekId
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getKekId() {
    return kekId;
  }

  public void setKekId(Long kekId) {
    this.kekId = kekId;
  }

  public Cards binBinNumber(String binBinNumber) {
    this.binBinNumber = binBinNumber;
    return this;
  }

   /**
   * Get binBinNumber
   * @return binBinNumber
  **/
  @ApiModelProperty(value = "")
  public String getBinBinNumber() {
    return binBinNumber;
  }

  public void setBinBinNumber(String binBinNumber) {
    this.binBinNumber = binBinNumber;
  }

  public Cards binIssuingCountryIsoNumber(String binIssuingCountryIsoNumber) {
    this.binIssuingCountryIsoNumber = binIssuingCountryIsoNumber;
    return this;
  }

   /**
   * Get binIssuingCountryIsoNumber
   * @return binIssuingCountryIsoNumber
  **/
  @ApiModelProperty(value = "")
  public String getBinIssuingCountryIsoNumber() {
    return binIssuingCountryIsoNumber;
  }

  public void setBinIssuingCountryIsoNumber(String binIssuingCountryIsoNumber) {
    this.binIssuingCountryIsoNumber = binIssuingCountryIsoNumber;
  }

  public Cards binId(Long binId) {
    this.binId = binId;
    return this;
  }

   /**
   * Get binId
   * @return binId
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getBinId() {
    return binId;
  }

  public void setBinId(Long binId) {
    this.binId = binId;
  }

  public Cards expirationMonth(Integer expirationMonth) {
    this.expirationMonth = expirationMonth;
    return this;
  }

   /**
   * Get expirationMonth
   * @return expirationMonth
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getExpirationMonth() {
    return expirationMonth;
  }

  public void setExpirationMonth(Integer expirationMonth) {
    this.expirationMonth = expirationMonth;
  }

  public Cards expirationYear(Integer expirationYear) {
    this.expirationYear = expirationYear;
    return this;
  }

   /**
   * Get expirationYear
   * @return expirationYear
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getExpirationYear() {
    return expirationYear;
  }

  public void setExpirationYear(Integer expirationYear) {
    this.expirationYear = expirationYear;
  }

  public Cards addressDataAddressLine(String addressDataAddressLine) {
    this.addressDataAddressLine = addressDataAddressLine;
    return this;
  }

   /**
   * Get addressDataAddressLine
   * @return addressDataAddressLine
  **/
  @ApiModelProperty(value = "")
  public String getAddressDataAddressLine() {
    return addressDataAddressLine;
  }

  public void setAddressDataAddressLine(String addressDataAddressLine) {
    this.addressDataAddressLine = addressDataAddressLine;
  }

  public Cards addressDataZip(String addressDataZip) {
    this.addressDataZip = addressDataZip;
    return this;
  }

   /**
   * Get addressDataZip
   * @return addressDataZip
  **/
  @ApiModelProperty(value = "")
  public String getAddressDataZip() {
    return addressDataZip;
  }

  public void setAddressDataZip(String addressDataZip) {
    this.addressDataZip = addressDataZip;
  }

  public Cards isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Get isDeleted
   * @return isDeleted
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean isIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public Cards version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public Cards pisMemberUniqueId(String pisMemberUniqueId) {
    this.pisMemberUniqueId = pisMemberUniqueId;
    return this;
  }

   /**
   * Get pisMemberUniqueId
   * @return pisMemberUniqueId
  **/
  @ApiModelProperty(value = "")
  public String getPisMemberUniqueId() {
    return pisMemberUniqueId;
  }

  public void setPisMemberUniqueId(String pisMemberUniqueId) {
    this.pisMemberUniqueId = pisMemberUniqueId;
  }

  public Cards pisMemberId(Long pisMemberId) {
    this.pisMemberId = pisMemberId;
    return this;
  }

   /**
   * Get pisMemberId
   * @return pisMemberId
  **/
  @ApiModelProperty(value = "")
  public Long getPisMemberId() {
    return pisMemberId;
  }

  public void setPisMemberId(Long pisMemberId) {
    this.pisMemberId = pisMemberId;
  }

  public Cards addressDataAddressLine2(String addressDataAddressLine2) {
    this.addressDataAddressLine2 = addressDataAddressLine2;
    return this;
  }

   /**
   * Get addressDataAddressLine2
   * @return addressDataAddressLine2
  **/
  @ApiModelProperty(value = "")
  public String getAddressDataAddressLine2() {
    return addressDataAddressLine2;
  }

  public void setAddressDataAddressLine2(String addressDataAddressLine2) {
    this.addressDataAddressLine2 = addressDataAddressLine2;
  }

  public Cards addressDataCity(String addressDataCity) {
    this.addressDataCity = addressDataCity;
    return this;
  }

   /**
   * Get addressDataCity
   * @return addressDataCity
  **/
  @ApiModelProperty(value = "")
  public String getAddressDataCity() {
    return addressDataCity;
  }

  public void setAddressDataCity(String addressDataCity) {
    this.addressDataCity = addressDataCity;
  }

  public Cards addressDataCountryId(Long addressDataCountryId) {
    this.addressDataCountryId = addressDataCountryId;
    return this;
  }

   /**
   * Get addressDataCountryId
   * @return addressDataCountryId
  **/
  @ApiModelProperty(value = "")
  public Long getAddressDataCountryId() {
    return addressDataCountryId;
  }

  public void setAddressDataCountryId(Long addressDataCountryId) {
    this.addressDataCountryId = addressDataCountryId;
  }

  public Cards addressDataStateId(Long addressDataStateId) {
    this.addressDataStateId = addressDataStateId;
    return this;
  }

   /**
   * Get addressDataStateId
   * @return addressDataStateId
  **/
  @ApiModelProperty(value = "")
  public Long getAddressDataStateId() {
    return addressDataStateId;
  }

  public void setAddressDataStateId(Long addressDataStateId) {
    this.addressDataStateId = addressDataStateId;
  }

  public Cards addressDataLegacyFullAddressLine(String addressDataLegacyFullAddressLine) {
    this.addressDataLegacyFullAddressLine = addressDataLegacyFullAddressLine;
    return this;
  }

   /**
   * Get addressDataLegacyFullAddressLine
   * @return addressDataLegacyFullAddressLine
  **/
  @ApiModelProperty(value = "")
  public String getAddressDataLegacyFullAddressLine() {
    return addressDataLegacyFullAddressLine;
  }

  public void setAddressDataLegacyFullAddressLine(String addressDataLegacyFullAddressLine) {
    this.addressDataLegacyFullAddressLine = addressDataLegacyFullAddressLine;
  }

  public Cards binIsPrepaid(Boolean binIsPrepaid) {
    this.binIsPrepaid = binIsPrepaid;
    return this;
  }

   /**
   * Get binIsPrepaid
   * @return binIsPrepaid
  **/
  @ApiModelProperty(value = "")
  public Boolean isBinIsPrepaid() {
    return binIsPrepaid;
  }

  public void setBinIsPrepaid(Boolean binIsPrepaid) {
    this.binIsPrepaid = binIsPrepaid;
  }

  public Cards token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public Cards kek(Keks kek) {
    this.kek = kek;
    return this;
  }

   /**
   * Get kek
   * @return kek
  **/
  @ApiModelProperty(value = "")
  public Keks getKek() {
    return kek;
  }

  public void setKek(Keks kek) {
    this.kek = kek;
  }

  public Cards cardClass(String cardClass) {
    this.cardClass = cardClass;
    return this;
  }

   /**
   * Get cardClass
   * @return cardClass
  **/
  @ApiModelProperty(value = "")
  public String getCardClass() {
    return cardClass;
  }

  public void setCardClass(String cardClass) {
    this.cardClass = cardClass;
  }

  public Cards productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @ApiModelProperty(value = "")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public Cards issuerBankName(String issuerBankName) {
    this.issuerBankName = issuerBankName;
    return this;
  }

   /**
   * Get issuerBankName
   * @return issuerBankName
  **/
  @ApiModelProperty(value = "")
  public String getIssuerBankName() {
    return issuerBankName;
  }

  public void setIssuerBankName(String issuerBankName) {
    this.issuerBankName = issuerBankName;
  }

  public Cards dekDataId(Long dekDataId) {
    this.dekDataId = dekDataId;
    return this;
  }

   /**
   * Get dekDataId
   * @return dekDataId
  **/
  @ApiModelProperty(value = "")
  public Long getDekDataId() {
    return dekDataId;
  }

  public void setDekDataId(Long dekDataId) {
    this.dekDataId = dekDataId;
  }

  public Cards dekData(DEKData dekData) {
    this.dekData = dekData;
    return this;
  }

   /**
   * Get dekData
   * @return dekData
  **/
  @ApiModelProperty(value = "")
  public DEKData getDekData() {
    return dekData;
  }

  public void setDekData(DEKData dekData) {
    this.dekData = dekData;
  }

  public Cards pisMember(Object pisMember) {
    this.pisMember = pisMember;
    return this;
  }

   /**
   * Get pisMember
   * @return pisMember
  **/
  @ApiModelProperty(value = "")
  public Object getPisMember() {
    return pisMember;
  }

  public void setPisMember(Object pisMember) {
    this.pisMember = pisMember;
  }

  public Cards accountUpdaterPendingCards(List<AccountUpdaterPendingCards> accountUpdaterPendingCards) {
    this.accountUpdaterPendingCards = accountUpdaterPendingCards;
    return this;
  }

  public Cards addAccountUpdaterPendingCardsItem(AccountUpdaterPendingCards accountUpdaterPendingCardsItem) {
    if (this.accountUpdaterPendingCards == null) {
      this.accountUpdaterPendingCards = new ArrayList<AccountUpdaterPendingCards>();
    }
    this.accountUpdaterPendingCards.add(accountUpdaterPendingCardsItem);
    return this;
  }

   /**
   * Get accountUpdaterPendingCards
   * @return accountUpdaterPendingCards
  **/
  @ApiModelProperty(value = "")
  public List<AccountUpdaterPendingCards> getAccountUpdaterPendingCards() {
    return accountUpdaterPendingCards;
  }

  public void setAccountUpdaterPendingCards(List<AccountUpdaterPendingCards> accountUpdaterPendingCards) {
    this.accountUpdaterPendingCards = accountUpdaterPendingCards;
  }

  public Cards cardStateLogs(List<CardStateLogs> cardStateLogs) {
    this.cardStateLogs = cardStateLogs;
    return this;
  }

  public Cards addCardStateLogsItem(CardStateLogs cardStateLogsItem) {
    if (this.cardStateLogs == null) {
      this.cardStateLogs = new ArrayList<CardStateLogs>();
    }
    this.cardStateLogs.add(cardStateLogsItem);
    return this;
  }

   /**
   * Get cardStateLogs
   * @return cardStateLogs
  **/
  @ApiModelProperty(value = "")
  public List<CardStateLogs> getCardStateLogs() {
    return cardStateLogs;
  }

  public void setCardStateLogs(List<CardStateLogs> cardStateLogs) {
    this.cardStateLogs = cardStateLogs;
  }

  public Cards fraudDetectionLogs(List<FraudDetectionLogs> fraudDetectionLogs) {
    this.fraudDetectionLogs = fraudDetectionLogs;
    return this;
  }

  public Cards addFraudDetectionLogsItem(FraudDetectionLogs fraudDetectionLogsItem) {
    if (this.fraudDetectionLogs == null) {
      this.fraudDetectionLogs = new ArrayList<FraudDetectionLogs>();
    }
    this.fraudDetectionLogs.add(fraudDetectionLogsItem);
    return this;
  }

   /**
   * Get fraudDetectionLogs
   * @return fraudDetectionLogs
  **/
  @ApiModelProperty(value = "")
  public List<FraudDetectionLogs> getFraudDetectionLogs() {
    return fraudDetectionLogs;
  }

  public void setFraudDetectionLogs(List<FraudDetectionLogs> fraudDetectionLogs) {
    this.fraudDetectionLogs = fraudDetectionLogs;
  }

  public Cards installmentPlanAuditLogs(List<InstallmentPlanAuditLogs> installmentPlanAuditLogs) {
    this.installmentPlanAuditLogs = installmentPlanAuditLogs;
    return this;
  }

  public Cards addInstallmentPlanAuditLogsItem(InstallmentPlanAuditLogs installmentPlanAuditLogsItem) {
    if (this.installmentPlanAuditLogs == null) {
      this.installmentPlanAuditLogs = new ArrayList<InstallmentPlanAuditLogs>();
    }
    this.installmentPlanAuditLogs.add(installmentPlanAuditLogsItem);
    return this;
  }

   /**
   * Get installmentPlanAuditLogs
   * @return installmentPlanAuditLogs
  **/
  @ApiModelProperty(value = "")
  public List<InstallmentPlanAuditLogs> getInstallmentPlanAuditLogs() {
    return installmentPlanAuditLogs;
  }

  public void setInstallmentPlanAuditLogs(List<InstallmentPlanAuditLogs> installmentPlanAuditLogs) {
    this.installmentPlanAuditLogs = installmentPlanAuditLogs;
  }

  public Cards installmentPlans(List<InstallmentPlans> installmentPlans) {
    this.installmentPlans = installmentPlans;
    return this;
  }

  public Cards addInstallmentPlansItem(InstallmentPlans installmentPlansItem) {
    if (this.installmentPlans == null) {
      this.installmentPlans = new ArrayList<InstallmentPlans>();
    }
    this.installmentPlans.add(installmentPlansItem);
    return this;
  }

   /**
   * Get installmentPlans
   * @return installmentPlans
  **/
  @ApiModelProperty(value = "")
  public List<InstallmentPlans> getInstallmentPlans() {
    return installmentPlans;
  }

  public void setInstallmentPlans(List<InstallmentPlans> installmentPlans) {
    this.installmentPlans = installmentPlans;
  }

  public Cards addressData(AddressData2 addressData) {
    this.addressData = addressData;
    return this;
  }

   /**
   * Get addressData
   * @return addressData
  **/
  @ApiModelProperty(value = "")
  public AddressData2 getAddressData() {
    return addressData;
  }

  public void setAddressData(AddressData2 addressData) {
    this.addressData = addressData;
  }

  public Cards encryptedNumber(String encryptedNumber) {
    this.encryptedNumber = encryptedNumber;
    return this;
  }

   /**
   * Get encryptedNumber
   * @return encryptedNumber
  **/
  @ApiModelProperty(value = "")
  public String getEncryptedNumber() {
    return encryptedNumber;
  }

  public void setEncryptedNumber(String encryptedNumber) {
    this.encryptedNumber = encryptedNumber;
  }

  public Cards dek(String dek) {
    this.dek = dek;
    return this;
  }

   /**
   * Get dek
   * @return dek
  **/
  @ApiModelProperty(value = "")
  public String getDek() {
    return dek;
  }

  public void setDek(String dek) {
    this.dek = dek;
  }

  public Cards maskedNumber(String maskedNumber) {
    this.maskedNumber = maskedNumber;
    return this;
  }

   /**
   * Get maskedNumber
   * @return maskedNumber
  **/
  @ApiModelProperty(value = "")
  public String getMaskedNumber() {
    return maskedNumber;
  }

  public void setMaskedNumber(String maskedNumber) {
    this.maskedNumber = maskedNumber;
  }

  public Cards cardHolderName(String cardHolderName) {
    this.cardHolderName = cardHolderName;
    return this;
  }

   /**
   * Get cardHolderName
   * @return cardHolderName
  **/
  @ApiModelProperty(value = "")
  public String getCardHolderName() {
    return cardHolderName;
  }

  public void setCardHolderName(String cardHolderName) {
    this.cardHolderName = cardHolderName;
  }

  public Cards binCardBrand(CardBrand binCardBrand) {
    this.binCardBrand = binCardBrand;
    return this;
  }

   /**
   * Get binCardBrand
   * @return binCardBrand
  **/
  @ApiModelProperty(required = true, value = "")
  public CardBrand getBinCardBrand() {
    return binCardBrand;
  }

  public void setBinCardBrand(CardBrand binCardBrand) {
    this.binCardBrand = binCardBrand;
  }

  public Cards binCardType(CardType binCardType) {
    this.binCardType = binCardType;
    return this;
  }

   /**
   * Get binCardType
   * @return binCardType
  **/
  @ApiModelProperty(required = true, value = "")
  public CardType getBinCardType() {
    return binCardType;
  }

  public void setBinCardType(CardType binCardType) {
    this.binCardType = binCardType;
  }

  public Cards cvv(String cvv) {
    this.cvv = cvv;
    return this;
  }

   /**
   * Get cvv
   * @return cvv
  **/
  @ApiModelProperty(value = "")
  public String getCvv() {
    return cvv;
  }

  public void setCvv(String cvv) {
    this.cvv = cvv;
  }

  public Cards bin(BinData bin) {
    this.bin = bin;
    return this;
  }

   /**
   * Get bin
   * @return bin
  **/
  @ApiModelProperty(value = "")
  public BinData getBin() {
    return bin;
  }

  public void setBin(BinData bin) {
    this.bin = bin;
  }

  public Cards country(Countries country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public Countries getCountry() {
    return country;
  }

  public void setCountry(Countries country) {
    this.country = country;
  }

  public Cards state(CountrySubdivisions state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public CountrySubdivisions getState() {
    return state;
  }

  public void setState(CountrySubdivisions state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cards cards = (Cards) o;
    return Objects.equals(this.id, cards.id) &&
        Objects.equals(this.kekId, cards.kekId) &&
        Objects.equals(this.binBinNumber, cards.binBinNumber) &&
        Objects.equals(this.binIssuingCountryIsoNumber, cards.binIssuingCountryIsoNumber) &&
        Objects.equals(this.binId, cards.binId) &&
        Objects.equals(this.expirationMonth, cards.expirationMonth) &&
        Objects.equals(this.expirationYear, cards.expirationYear) &&
        Objects.equals(this.addressDataAddressLine, cards.addressDataAddressLine) &&
        Objects.equals(this.addressDataZip, cards.addressDataZip) &&
        Objects.equals(this.isDeleted, cards.isDeleted) &&
        Objects.equals(this.version, cards.version) &&
        Objects.equals(this.pisMemberUniqueId, cards.pisMemberUniqueId) &&
        Objects.equals(this.pisMemberId, cards.pisMemberId) &&
        Objects.equals(this.addressDataAddressLine2, cards.addressDataAddressLine2) &&
        Objects.equals(this.addressDataCity, cards.addressDataCity) &&
        Objects.equals(this.addressDataCountryId, cards.addressDataCountryId) &&
        Objects.equals(this.addressDataStateId, cards.addressDataStateId) &&
        Objects.equals(this.addressDataLegacyFullAddressLine, cards.addressDataLegacyFullAddressLine) &&
        Objects.equals(this.binIsPrepaid, cards.binIsPrepaid) &&
        Objects.equals(this.token, cards.token) &&
        Objects.equals(this.kek, cards.kek) &&
        Objects.equals(this.cardClass, cards.cardClass) &&
        Objects.equals(this.productId, cards.productId) &&
        Objects.equals(this.issuerBankName, cards.issuerBankName) &&
        Objects.equals(this.dekDataId, cards.dekDataId) &&
        Objects.equals(this.dekData, cards.dekData) &&
        Objects.equals(this.pisMember, cards.pisMember) &&
        Objects.equals(this.accountUpdaterPendingCards, cards.accountUpdaterPendingCards) &&
        Objects.equals(this.cardStateLogs, cards.cardStateLogs) &&
        Objects.equals(this.fraudDetectionLogs, cards.fraudDetectionLogs) &&
        Objects.equals(this.installmentPlanAuditLogs, cards.installmentPlanAuditLogs) &&
        Objects.equals(this.installmentPlans, cards.installmentPlans) &&
        Objects.equals(this.addressData, cards.addressData) &&
        Objects.equals(this.encryptedNumber, cards.encryptedNumber) &&
        Objects.equals(this.dek, cards.dek) &&
        Objects.equals(this.maskedNumber, cards.maskedNumber) &&
        Objects.equals(this.cardHolderName, cards.cardHolderName) &&
        Objects.equals(this.binCardBrand, cards.binCardBrand) &&
        Objects.equals(this.binCardType, cards.binCardType) &&
        Objects.equals(this.cvv, cards.cvv) &&
        Objects.equals(this.bin, cards.bin) &&
        Objects.equals(this.country, cards.country) &&
        Objects.equals(this.state, cards.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, kekId, binBinNumber, binIssuingCountryIsoNumber, binId, expirationMonth, expirationYear, addressDataAddressLine, addressDataZip, isDeleted, version, pisMemberUniqueId, pisMemberId, addressDataAddressLine2, addressDataCity, addressDataCountryId, addressDataStateId, addressDataLegacyFullAddressLine, binIsPrepaid, token, kek, cardClass, productId, issuerBankName, dekDataId, dekData, pisMember, accountUpdaterPendingCards, cardStateLogs, fraudDetectionLogs, installmentPlanAuditLogs, installmentPlans, addressData, encryptedNumber, dek, maskedNumber, cardHolderName, binCardBrand, binCardType, cvv, bin, country, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cards {\n");
    
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kekId: ").append(toIndentedString(kekId)).append("\n");
    sb.append("    binBinNumber: ").append(toIndentedString(binBinNumber)).append("\n");
    sb.append("    binIssuingCountryIsoNumber: ").append(toIndentedString(binIssuingCountryIsoNumber)).append("\n");
    sb.append("    binId: ").append(toIndentedString(binId)).append("\n");
    sb.append("    expirationMonth: ").append(toIndentedString(expirationMonth)).append("\n");
    sb.append("    expirationYear: ").append(toIndentedString(expirationYear)).append("\n");
    sb.append("    addressDataAddressLine: ").append(toIndentedString(addressDataAddressLine)).append("\n");
    sb.append("    addressDataZip: ").append(toIndentedString(addressDataZip)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    pisMemberUniqueId: ").append(toIndentedString(pisMemberUniqueId)).append("\n");
    sb.append("    pisMemberId: ").append(toIndentedString(pisMemberId)).append("\n");
    sb.append("    addressDataAddressLine2: ").append(toIndentedString(addressDataAddressLine2)).append("\n");
    sb.append("    addressDataCity: ").append(toIndentedString(addressDataCity)).append("\n");
    sb.append("    addressDataCountryId: ").append(toIndentedString(addressDataCountryId)).append("\n");
    sb.append("    addressDataStateId: ").append(toIndentedString(addressDataStateId)).append("\n");
    sb.append("    addressDataLegacyFullAddressLine: ").append(toIndentedString(addressDataLegacyFullAddressLine)).append("\n");
    sb.append("    binIsPrepaid: ").append(toIndentedString(binIsPrepaid)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    kek: ").append(toIndentedString(kek)).append("\n");
    sb.append("    cardClass: ").append(toIndentedString(cardClass)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    issuerBankName: ").append(toIndentedString(issuerBankName)).append("\n");
    sb.append("    dekDataId: ").append(toIndentedString(dekDataId)).append("\n");
    sb.append("    dekData: ").append(toIndentedString(dekData)).append("\n");
    sb.append("    pisMember: ").append(toIndentedString(pisMember)).append("\n");
    sb.append("    accountUpdaterPendingCards: ").append(toIndentedString(accountUpdaterPendingCards)).append("\n");
    sb.append("    cardStateLogs: ").append(toIndentedString(cardStateLogs)).append("\n");
    sb.append("    fraudDetectionLogs: ").append(toIndentedString(fraudDetectionLogs)).append("\n");
    sb.append("    installmentPlanAuditLogs: ").append(toIndentedString(installmentPlanAuditLogs)).append("\n");
    sb.append("    installmentPlans: ").append(toIndentedString(installmentPlans)).append("\n");
    sb.append("    addressData: ").append(toIndentedString(addressData)).append("\n");
    sb.append("    encryptedNumber: ").append(toIndentedString(encryptedNumber)).append("\n");
    sb.append("    dek: ").append(toIndentedString(dek)).append("\n");
    sb.append("    maskedNumber: ").append(toIndentedString(maskedNumber)).append("\n");
    sb.append("    cardHolderName: ").append(toIndentedString(cardHolderName)).append("\n");
    sb.append("    binCardBrand: ").append(toIndentedString(binCardBrand)).append("\n");
    sb.append("    binCardType: ").append(toIndentedString(binCardType)).append("\n");
    sb.append("    cvv: ").append(toIndentedString(cvv)).append("\n");
    sb.append("    bin: ").append(toIndentedString(bin)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

