/*
 * splitit-web-api-public-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.splitit.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.splitit.sdk.model.EntityBase;
import com.splitit.sdk.model.PaymentGatewayTransactionLogs;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PaymentGatewayTransactionAsyncLogs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-06T09:33:27.783Z")
public class PaymentGatewayTransactionAsyncLogs  {
  @SerializedName("Id")
  private Long id = null;

  @SerializedName("Result")
  private Boolean result = null;

  @SerializedName("ManualVerification")
  private Boolean manualVerification = null;

  @SerializedName("ResponseLog")
  private String responseLog = null;

  @SerializedName("ReferenceGatewayTransactionId")
  private String referenceGatewayTransactionId = null;

  @SerializedName("ReferencePaymentGatewayTransactionLogId")
  private Long referencePaymentGatewayTransactionLogId = null;

  @SerializedName("ReferencePaymentGatewayTransactionLog")
  private PaymentGatewayTransactionLogs referencePaymentGatewayTransactionLog = null;

  public PaymentGatewayTransactionAsyncLogs id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PaymentGatewayTransactionAsyncLogs result(Boolean result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean isResult() {
    return result;
  }

  public void setResult(Boolean result) {
    this.result = result;
  }

  public PaymentGatewayTransactionAsyncLogs manualVerification(Boolean manualVerification) {
    this.manualVerification = manualVerification;
    return this;
  }

   /**
   * Get manualVerification
   * @return manualVerification
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean isManualVerification() {
    return manualVerification;
  }

  public void setManualVerification(Boolean manualVerification) {
    this.manualVerification = manualVerification;
  }

  public PaymentGatewayTransactionAsyncLogs responseLog(String responseLog) {
    this.responseLog = responseLog;
    return this;
  }

   /**
   * Get responseLog
   * @return responseLog
  **/
  @ApiModelProperty(value = "")
  public String getResponseLog() {
    return responseLog;
  }

  public void setResponseLog(String responseLog) {
    this.responseLog = responseLog;
  }

  public PaymentGatewayTransactionAsyncLogs referenceGatewayTransactionId(String referenceGatewayTransactionId) {
    this.referenceGatewayTransactionId = referenceGatewayTransactionId;
    return this;
  }

   /**
   * Get referenceGatewayTransactionId
   * @return referenceGatewayTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getReferenceGatewayTransactionId() {
    return referenceGatewayTransactionId;
  }

  public void setReferenceGatewayTransactionId(String referenceGatewayTransactionId) {
    this.referenceGatewayTransactionId = referenceGatewayTransactionId;
  }

  public PaymentGatewayTransactionAsyncLogs referencePaymentGatewayTransactionLogId(Long referencePaymentGatewayTransactionLogId) {
    this.referencePaymentGatewayTransactionLogId = referencePaymentGatewayTransactionLogId;
    return this;
  }

   /**
   * Get referencePaymentGatewayTransactionLogId
   * @return referencePaymentGatewayTransactionLogId
  **/
  @ApiModelProperty(value = "")
  public Long getReferencePaymentGatewayTransactionLogId() {
    return referencePaymentGatewayTransactionLogId;
  }

  public void setReferencePaymentGatewayTransactionLogId(Long referencePaymentGatewayTransactionLogId) {
    this.referencePaymentGatewayTransactionLogId = referencePaymentGatewayTransactionLogId;
  }

  public PaymentGatewayTransactionAsyncLogs referencePaymentGatewayTransactionLog(PaymentGatewayTransactionLogs referencePaymentGatewayTransactionLog) {
    this.referencePaymentGatewayTransactionLog = referencePaymentGatewayTransactionLog;
    return this;
  }

   /**
   * Get referencePaymentGatewayTransactionLog
   * @return referencePaymentGatewayTransactionLog
  **/
  @ApiModelProperty(value = "")
  public PaymentGatewayTransactionLogs getReferencePaymentGatewayTransactionLog() {
    return referencePaymentGatewayTransactionLog;
  }

  public void setReferencePaymentGatewayTransactionLog(PaymentGatewayTransactionLogs referencePaymentGatewayTransactionLog) {
    this.referencePaymentGatewayTransactionLog = referencePaymentGatewayTransactionLog;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentGatewayTransactionAsyncLogs paymentGatewayTransactionAsyncLogs = (PaymentGatewayTransactionAsyncLogs) o;
    return Objects.equals(this.id, paymentGatewayTransactionAsyncLogs.id) &&
        Objects.equals(this.result, paymentGatewayTransactionAsyncLogs.result) &&
        Objects.equals(this.manualVerification, paymentGatewayTransactionAsyncLogs.manualVerification) &&
        Objects.equals(this.responseLog, paymentGatewayTransactionAsyncLogs.responseLog) &&
        Objects.equals(this.referenceGatewayTransactionId, paymentGatewayTransactionAsyncLogs.referenceGatewayTransactionId) &&
        Objects.equals(this.referencePaymentGatewayTransactionLogId, paymentGatewayTransactionAsyncLogs.referencePaymentGatewayTransactionLogId) &&
        Objects.equals(this.referencePaymentGatewayTransactionLog, paymentGatewayTransactionAsyncLogs.referencePaymentGatewayTransactionLog);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, result, manualVerification, responseLog, referenceGatewayTransactionId, referencePaymentGatewayTransactionLogId, referencePaymentGatewayTransactionLog);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentGatewayTransactionAsyncLogs {\n");
    
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    manualVerification: ").append(toIndentedString(manualVerification)).append("\n");
    sb.append("    responseLog: ").append(toIndentedString(responseLog)).append("\n");
    sb.append("    referenceGatewayTransactionId: ").append(toIndentedString(referenceGatewayTransactionId)).append("\n");
    sb.append("    referencePaymentGatewayTransactionLogId: ").append(toIndentedString(referencePaymentGatewayTransactionLogId)).append("\n");
    sb.append("    referencePaymentGatewayTransactionLog: ").append(toIndentedString(referencePaymentGatewayTransactionLog)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

