/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AccountUpdaterProvider } from './accountUpdaterProvider';
import { Cards } from './cards';

export class AccountUpdaterPendingCardsAllOf {
    'cardId': number;
    'exportTime'?: Date;
    'exportBatchId'?: string;
    'exportRecordId'?: string;
    'importTime'?: Date;
    'card'?: Cards;
    'accountUpdater': AccountUpdaterProvider;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cardId",
            "baseName": "CardId",
            "type": "number"
        },
        {
            "name": "exportTime",
            "baseName": "ExportTime",
            "type": "Date"
        },
        {
            "name": "exportBatchId",
            "baseName": "ExportBatchId",
            "type": "string"
        },
        {
            "name": "exportRecordId",
            "baseName": "ExportRecordId",
            "type": "string"
        },
        {
            "name": "importTime",
            "baseName": "ImportTime",
            "type": "Date"
        },
        {
            "name": "card",
            "baseName": "Card",
            "type": "Cards"
        },
        {
            "name": "accountUpdater",
            "baseName": "AccountUpdater",
            "type": "AccountUpdaterProvider"
        }    ];

    static getAttributeTypeMap() {
        return AccountUpdaterPendingCardsAllOf.attributeTypeMap;
    }
}

