/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { EmailAuditLogsAllOf } from './emailAuditLogsAllOf';
import { EntityBase } from './entityBase';
import { InstallmentPlans } from './installmentPlans';
import { SystemEmailsTypes } from './systemEmailsTypes';
import { UserType } from './userType';

export class EmailAuditLogs {
    'id': number;
    'installmentPlanId'?: number;
    'userUniqueId'?: string;
    'userId'?: number;
    'emailAddress'?: string;
    'externalIdentifier'?: string;
    'installmentPlan'?: InstallmentPlans;
    'userType'?: UserType;
    'emailType': SystemEmailsTypes;
    'emailHtmlBodyFilename'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "Id",
            "type": "number"
        },
        {
            "name": "installmentPlanId",
            "baseName": "InstallmentPlanId",
            "type": "number"
        },
        {
            "name": "userUniqueId",
            "baseName": "UserUniqueId",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "UserId",
            "type": "number"
        },
        {
            "name": "emailAddress",
            "baseName": "EmailAddress",
            "type": "string"
        },
        {
            "name": "externalIdentifier",
            "baseName": "ExternalIdentifier",
            "type": "string"
        },
        {
            "name": "installmentPlan",
            "baseName": "InstallmentPlan",
            "type": "InstallmentPlans"
        },
        {
            "name": "userType",
            "baseName": "UserType",
            "type": "UserType"
        },
        {
            "name": "emailType",
            "baseName": "EmailType",
            "type": "SystemEmailsTypes"
        },
        {
            "name": "emailHtmlBodyFilename",
            "baseName": "EmailHtmlBodyFilename",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EmailAuditLogs.attributeTypeMap;
    }
}

