/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { FeeRates } from './feeRates';
import { RangeType } from './rangeType';

export class FeeRateCollectionsAllOf {
    'rangeType': RangeType;
    'feeRates'?: Array<FeeRates>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rangeType",
            "baseName": "RangeType",
            "type": "RangeType"
        },
        {
            "name": "feeRates",
            "baseName": "FeeRates",
            "type": "Array<FeeRates>"
        }    ];

    static getAttributeTypeMap() {
        return FeeRateCollectionsAllOf.attributeTypeMap;
    }
}

