/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { EntityBase } from './entityBase';
import { FundingCollectDocumentDetails } from './fundingCollectDocumentDetails';
import { FundingPayDocumentDetailsAllOf } from './fundingPayDocumentDetailsAllOf';
import { InstallmentPlans } from './installmentPlans';
import { PayDocuments } from './payDocuments';

export class FundingPayDocumentDetails {
    'id': number;
    'payDocumentId'?: number;
    'planId'?: number;
    'amount': number;
    'plan'?: InstallmentPlans;
    'collectDocumentDetailsId'?: number;
    'collectDocumentDetails'?: FundingCollectDocumentDetails;
    'payDocument'?: PayDocuments;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "Id",
            "type": "number"
        },
        {
            "name": "payDocumentId",
            "baseName": "PayDocumentId",
            "type": "number"
        },
        {
            "name": "planId",
            "baseName": "PlanId",
            "type": "number"
        },
        {
            "name": "amount",
            "baseName": "Amount",
            "type": "number"
        },
        {
            "name": "plan",
            "baseName": "Plan",
            "type": "InstallmentPlans"
        },
        {
            "name": "collectDocumentDetailsId",
            "baseName": "CollectDocumentDetailsId",
            "type": "number"
        },
        {
            "name": "collectDocumentDetails",
            "baseName": "CollectDocumentDetails",
            "type": "FundingCollectDocumentDetails"
        },
        {
            "name": "payDocument",
            "baseName": "PayDocument",
            "type": "PayDocuments"
        }    ];

    static getAttributeTypeMap() {
        return FundingPayDocumentDetails.attributeTypeMap;
    }
}

