/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { InitiateInstallmentsPlanResponseAllOf } from './initiateInstallmentsPlanResponseAllOf';
import { InstallmentPlan } from './installmentPlan';
import { InstallmentPlanResponse } from './installmentPlanResponse';
import { ResponseHeader } from './responseHeader';

export class InitiateInstallmentsPlanResponse {
    'responseHeader'?: ResponseHeader;
    'installmentPlan'?: InstallmentPlan;
    'checkoutUrl'?: string;
    'approvalUrl'?: string;
    'termsAndConditionsUrl'?: string;
    'privacyPolicyUrl'?: string;
    'installmentPlanInfoUrl'?: string;
    'publicToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "responseHeader",
            "baseName": "ResponseHeader",
            "type": "ResponseHeader"
        },
        {
            "name": "installmentPlan",
            "baseName": "InstallmentPlan",
            "type": "InstallmentPlan"
        },
        {
            "name": "checkoutUrl",
            "baseName": "CheckoutUrl",
            "type": "string"
        },
        {
            "name": "approvalUrl",
            "baseName": "ApprovalUrl",
            "type": "string"
        },
        {
            "name": "termsAndConditionsUrl",
            "baseName": "TermsAndConditionsUrl",
            "type": "string"
        },
        {
            "name": "privacyPolicyUrl",
            "baseName": "PrivacyPolicyUrl",
            "type": "string"
        },
        {
            "name": "installmentPlanInfoUrl",
            "baseName": "InstallmentPlanInfoUrl",
            "type": "string"
        },
        {
            "name": "publicToken",
            "baseName": "PublicToken",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InitiateInstallmentsPlanResponse.attributeTypeMap;
    }
}

