/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Cards } from './cards';
import { InstallmentPlans } from './installmentPlans';
import { PisErrorCodes } from './pisErrorCodes';

export class InstallmentPlanAuditLogsAllOf {
    'installmentPlanId'?: number;
    'creatingIPAddress'?: string;
    'cardId'?: number;
    'card'?: Cards;
    'installmentPlan'?: InstallmentPlans;
    'errorCode'?: PisErrorCodes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "installmentPlanId",
            "baseName": "InstallmentPlanId",
            "type": "number"
        },
        {
            "name": "creatingIPAddress",
            "baseName": "CreatingIPAddress",
            "type": "string"
        },
        {
            "name": "cardId",
            "baseName": "CardId",
            "type": "number"
        },
        {
            "name": "card",
            "baseName": "Card",
            "type": "Cards"
        },
        {
            "name": "installmentPlan",
            "baseName": "InstallmentPlan",
            "type": "InstallmentPlans"
        },
        {
            "name": "errorCode",
            "baseName": "ErrorCode",
            "type": "PisErrorCodes"
        }    ];

    static getAttributeTypeMap() {
        return InstallmentPlanAuditLogsAllOf.attributeTypeMap;
    }
}

