/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { SessionAvailibility } from './sessionAvailibility';
import { UserType } from './userType';
import { VersionedTouchPoints } from './versionedTouchPoints';

export class PisSessionsAllOf {
    'sessionId'?: string;
    'lastAccessTime': Date;
    'userId'?: number;
    'userUniqueId'?: string;
    'installmentPlanNumber'?: string;
    'versionedTouchPointId'?: number;
    'sessionValidPeriodInMinutes': number;
    'versionedTouchPoint'?: VersionedTouchPoints;
    'userType'?: UserType;
    'sessionAvailibility': SessionAvailibility;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sessionId",
            "baseName": "SessionId",
            "type": "string"
        },
        {
            "name": "lastAccessTime",
            "baseName": "LastAccessTime",
            "type": "Date"
        },
        {
            "name": "userId",
            "baseName": "UserId",
            "type": "number"
        },
        {
            "name": "userUniqueId",
            "baseName": "UserUniqueId",
            "type": "string"
        },
        {
            "name": "installmentPlanNumber",
            "baseName": "InstallmentPlanNumber",
            "type": "string"
        },
        {
            "name": "versionedTouchPointId",
            "baseName": "VersionedTouchPointId",
            "type": "number"
        },
        {
            "name": "sessionValidPeriodInMinutes",
            "baseName": "SessionValidPeriodInMinutes",
            "type": "number"
        },
        {
            "name": "versionedTouchPoint",
            "baseName": "VersionedTouchPoint",
            "type": "VersionedTouchPoints"
        },
        {
            "name": "userType",
            "baseName": "UserType",
            "type": "UserType"
        },
        {
            "name": "sessionAvailibility",
            "baseName": "SessionAvailibility",
            "type": "SessionAvailibility"
        }    ];

    static getAttributeTypeMap() {
        return PisSessionsAllOf.attributeTypeMap;
    }
}

