/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ScheduleElements } from './scheduleElements';

export class Schedule {
    'numberOfInstallments': number;
    'deposit': boolean;
    'elements'?: Array<ScheduleElements>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numberOfInstallments",
            "baseName": "NumberOfInstallments",
            "type": "number"
        },
        {
            "name": "deposit",
            "baseName": "Deposit",
            "type": "boolean"
        },
        {
            "name": "elements",
            "baseName": "Elements",
            "type": "Array<ScheduleElements>"
        }    ];

    static getAttributeTypeMap() {
        return Schedule.attributeTypeMap;
    }
}

