/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class TouchPoint {
    'code'?: string;
    'version'?: string;
    'subVersion'?: string;
    'versionedTouchpointId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "Code",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "Version",
            "type": "string"
        },
        {
            "name": "subVersion",
            "baseName": "SubVersion",
            "type": "string"
        },
        {
            "name": "versionedTouchpointId",
            "baseName": "VersionedTouchpointId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TouchPoint.attributeTypeMap;
    }
}

