/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AccountingParty {
    Scp = 'Scp',
    Agent = 'Agent',
    Merchant = 'Merchant',
    SplititUsa = 'SplititUsa',
    SplititCapital = 'SplititCapital'
}

export function AccountingPartyFromJSON(json: any): AccountingParty {
    return AccountingPartyFromJSONTyped(json, false);
}

export function AccountingPartyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountingParty {
    return json as AccountingParty;
}

export function AccountingPartyToJSON(value?: AccountingParty | null): any {
    return value as any;
}

