/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiUserPasswordHistories,
    ApiUserPasswordHistoriesFromJSON,
    ApiUserPasswordHistoriesFromJSONTyped,
    ApiUserPasswordHistoriesToJSON,
    IUserPasswordHistory,
    IUserPasswordHistoryFromJSON,
    IUserPasswordHistoryFromJSONTyped,
    IUserPasswordHistoryToJSON,
    Merchants,
    MerchantsFromJSON,
    MerchantsFromJSONTyped,
    MerchantsToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApiUsersAllOf
 */
export interface ApiUsersAllOf {
    /**
     * 
     * @type {string}
     * @memberof ApiUsersAllOf
     */
    crmId?: string;
    /**
     * 
     * @type {Merchants}
     * @memberof ApiUsersAllOf
     */
    merchant?: Merchants;
    /**
     * 
     * @type {Array<ApiUserPasswordHistories>}
     * @memberof ApiUsersAllOf
     */
    apiUserPasswordHistories?: Array<ApiUserPasswordHistories>;
    /**
     * 
     * @type {number}
     * @memberof ApiUsersAllOf
     */
    merchantId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiUsersAllOf
     */
    merchantName?: string;
    /**
     * 
     * @type {IUserPasswordHistory}
     * @memberof ApiUsersAllOf
     */
    password?: IUserPasswordHistory;
}

export function ApiUsersAllOfFromJSON(json: any): ApiUsersAllOf {
    return ApiUsersAllOfFromJSONTyped(json, false);
}

export function ApiUsersAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUsersAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'crmId': !exists(json, 'CrmId') ? undefined : json['CrmId'],
        'merchant': !exists(json, 'Merchant') ? undefined : MerchantsFromJSON(json['Merchant']),
        'apiUserPasswordHistories': !exists(json, 'ApiUserPasswordHistories') ? undefined : ((json['ApiUserPasswordHistories'] as Array<any>).map(ApiUserPasswordHistoriesFromJSON)),
        'merchantId': json['MerchantId'],
        'merchantName': !exists(json, 'MerchantName') ? undefined : json['MerchantName'],
        'password': !exists(json, 'Password') ? undefined : IUserPasswordHistoryFromJSON(json['Password']),
    };
}

export function ApiUsersAllOfToJSON(value?: ApiUsersAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CrmId': value.crmId,
        'Merchant': MerchantsToJSON(value.merchant),
        'ApiUserPasswordHistories': value.apiUserPasswordHistories === undefined ? undefined : ((value.apiUserPasswordHistories as Array<any>).map(ApiUserPasswordHistoriesToJSON)),
        'MerchantId': value.merchantId,
        'MerchantName': value.merchantName,
        'Password': IUserPasswordHistoryToJSON(value.password),
    };
}


