/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CurrenciesAllOf,
    CurrenciesAllOfFromJSON,
    CurrenciesAllOfFromJSONTyped,
    CurrenciesAllOfToJSON,
    EntityBase,
    EntityBaseFromJSON,
    EntityBaseFromJSONTyped,
    EntityBaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface Currencies
 */
export interface Currencies {
    /**
     * 
     * @type {number}
     * @memberof Currencies
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Currencies
     */
    currencyCode: string;
    /**
     * 
     * @type {string}
     * @memberof Currencies
     */
    currencyName: string;
    /**
     * 
     * @type {string}
     * @memberof Currencies
     */
    currencySymbol: string;
    /**
     * 
     * @type {string}
     * @memberof Currencies
     */
    currencyIsoNumber: string;
    /**
     * 
     * @type {number}
     * @memberof Currencies
     */
    decimalPlaces: number;
}

export function CurrenciesFromJSON(json: any): Currencies {
    return CurrenciesFromJSONTyped(json, false);
}

export function CurrenciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Currencies {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['Id'],
        'currencyCode': json['CurrencyCode'],
        'currencyName': json['CurrencyName'],
        'currencySymbol': json['CurrencySymbol'],
        'currencyIsoNumber': json['CurrencyIsoNumber'],
        'decimalPlaces': json['DecimalPlaces'],
    };
}

export function CurrenciesToJSON(value?: Currencies | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'CurrencyCode': value.currencyCode,
        'CurrencyName': value.currencyName,
        'CurrencySymbol': value.currencySymbol,
        'CurrencyIsoNumber': value.currencyIsoNumber,
        'DecimalPlaces': value.decimalPlaces,
    };
}


