/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BuRef,
    BuRefFromJSON,
    BuRefFromJSONTyped,
    BuRefToJSON,
} from './';

/**
 * 
 * @export
 * @interface ExtendedInstallmentPlanAllOf
 */
export interface ExtendedInstallmentPlanAllOf {
    /**
     * 
     * @type {BuRef}
     * @memberof ExtendedInstallmentPlanAllOf
     */
    businessUnit?: BuRef;
    /**
     * 
     * @type {Date}
     * @memberof ExtendedInstallmentPlanAllOf
     */
    shopperPaymentRequestTime?: Date;
}

export function ExtendedInstallmentPlanAllOfFromJSON(json: any): ExtendedInstallmentPlanAllOf {
    return ExtendedInstallmentPlanAllOfFromJSONTyped(json, false);
}

export function ExtendedInstallmentPlanAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedInstallmentPlanAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'businessUnit': !exists(json, 'BusinessUnit') ? undefined : BuRefFromJSON(json['BusinessUnit']),
        'shopperPaymentRequestTime': !exists(json, 'ShopperPaymentRequestTime') ? undefined : (new Date(json['ShopperPaymentRequestTime'])),
    };
}

export function ExtendedInstallmentPlanAllOfToJSON(value?: ExtendedInstallmentPlanAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BusinessUnit': BuRefToJSON(value.businessUnit),
        'ShopperPaymentRequestTime': value.shopperPaymentRequestTime === undefined ? undefined : (value.shopperPaymentRequestTime.toISOString()),
    };
}


