/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Get3DSecureParametersRequest
 */
export interface Get3DSecureParametersRequest {
    /**
     * 
     * @type {string}
     * @memberof Get3DSecureParametersRequest
     */
    installmentPlanNumber?: string;
}

export function Get3DSecureParametersRequestFromJSON(json: any): Get3DSecureParametersRequest {
    return Get3DSecureParametersRequestFromJSONTyped(json, false);
}

export function Get3DSecureParametersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get3DSecureParametersRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'installmentPlanNumber': !exists(json, 'InstallmentPlanNumber') ? undefined : json['InstallmentPlanNumber'],
    };
}

export function Get3DSecureParametersRequestToJSON(value?: Get3DSecureParametersRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'InstallmentPlanNumber': value.installmentPlanNumber,
    };
}


