/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExtendedInstallmentPlan,
    ExtendedInstallmentPlanFromJSON,
    ExtendedInstallmentPlanFromJSONTyped,
    ExtendedInstallmentPlanToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetInstallmentsPlanExtendedResponseAllOf
 */
export interface GetInstallmentsPlanExtendedResponseAllOf {
    /**
     * 
     * @type {Array<ExtendedInstallmentPlan>}
     * @memberof GetInstallmentsPlanExtendedResponseAllOf
     */
    plansList?: Array<ExtendedInstallmentPlan>;
}

export function GetInstallmentsPlanExtendedResponseAllOfFromJSON(json: any): GetInstallmentsPlanExtendedResponseAllOf {
    return GetInstallmentsPlanExtendedResponseAllOfFromJSONTyped(json, false);
}

export function GetInstallmentsPlanExtendedResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInstallmentsPlanExtendedResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plansList': !exists(json, 'PlansList') ? undefined : ((json['PlansList'] as Array<any>).map(ExtendedInstallmentPlanFromJSON)),
    };
}

export function GetInstallmentsPlanExtendedResponseAllOfToJSON(value?: GetInstallmentsPlanExtendedResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PlansList': value.plansList === undefined ? undefined : ((value.plansList as Array<any>).map(ExtendedInstallmentPlanToJSON)),
    };
}


