/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Currencies,
    CurrenciesFromJSON,
    CurrenciesFromJSONTyped,
    CurrenciesToJSON,
    FeesRuleDatas,
    FeesRuleDatasFromJSON,
    FeesRuleDatasFromJSONTyped,
    FeesRuleDatasToJSON,
    FundingRuleDataScpProviderSetting,
    FundingRuleDataScpProviderSettingFromJSON,
    FundingRuleDataScpProviderSettingFromJSONTyped,
    FundingRuleDataScpProviderSettingToJSON,
    InstallmentPlans,
    InstallmentPlansFromJSON,
    InstallmentPlansFromJSONTyped,
    InstallmentPlansToJSON,
} from './';

/**
 * 
 * @export
 * @interface InstallmentPlanTerminalDatasAllOf
 */
export interface InstallmentPlanTerminalDatasAllOf {
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    scpVariableCostAnnualPercent: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    scpFundingPercent: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    scpReservePoolPercent: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    scpReturnMerchantMaxDays: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    scpRevenueSharePercent: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    scpFixedCost: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    accountingCurrencyId?: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    fundingRuleScpSettingId?: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    feesRuleDataId?: number;
    /**
     * 
     * @type {Currencies}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    accountingCurrency?: Currencies;
    /**
     * 
     * @type {FeesRuleDatas}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    feesRuleData?: FeesRuleDatas;
    /**
     * 
     * @type {FundingRuleDataScpProviderSetting}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    fundingRuleScpSetting?: FundingRuleDataScpProviderSetting;
    /**
     * 
     * @type {Array<InstallmentPlans>}
     * @memberof InstallmentPlanTerminalDatasAllOf
     */
    installmentPlans?: Array<InstallmentPlans>;
}

export function InstallmentPlanTerminalDatasAllOfFromJSON(json: any): InstallmentPlanTerminalDatasAllOf {
    return InstallmentPlanTerminalDatasAllOfFromJSONTyped(json, false);
}

export function InstallmentPlanTerminalDatasAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallmentPlanTerminalDatasAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scpVariableCostAnnualPercent': json['ScpVariableCostAnnualPercent'],
        'scpFundingPercent': json['ScpFundingPercent'],
        'scpReservePoolPercent': json['ScpReservePoolPercent'],
        'scpReturnMerchantMaxDays': json['ScpReturnMerchantMaxDays'],
        'scpRevenueSharePercent': json['ScpRevenueSharePercent'],
        'scpFixedCost': json['ScpFixedCost'],
        'accountingCurrencyId': !exists(json, 'AccountingCurrencyId') ? undefined : json['AccountingCurrencyId'],
        'fundingRuleScpSettingId': !exists(json, 'FundingRuleScpSettingId') ? undefined : json['FundingRuleScpSettingId'],
        'feesRuleDataId': !exists(json, 'FeesRuleDataId') ? undefined : json['FeesRuleDataId'],
        'accountingCurrency': !exists(json, 'AccountingCurrency') ? undefined : CurrenciesFromJSON(json['AccountingCurrency']),
        'feesRuleData': !exists(json, 'FeesRuleData') ? undefined : FeesRuleDatasFromJSON(json['FeesRuleData']),
        'fundingRuleScpSetting': !exists(json, 'FundingRuleScpSetting') ? undefined : FundingRuleDataScpProviderSettingFromJSON(json['FundingRuleScpSetting']),
        'installmentPlans': !exists(json, 'InstallmentPlans') ? undefined : ((json['InstallmentPlans'] as Array<any>).map(InstallmentPlansFromJSON)),
    };
}

export function InstallmentPlanTerminalDatasAllOfToJSON(value?: InstallmentPlanTerminalDatasAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ScpVariableCostAnnualPercent': value.scpVariableCostAnnualPercent,
        'ScpFundingPercent': value.scpFundingPercent,
        'ScpReservePoolPercent': value.scpReservePoolPercent,
        'ScpReturnMerchantMaxDays': value.scpReturnMerchantMaxDays,
        'ScpRevenueSharePercent': value.scpRevenueSharePercent,
        'ScpFixedCost': value.scpFixedCost,
        'AccountingCurrencyId': value.accountingCurrencyId,
        'FundingRuleScpSettingId': value.fundingRuleScpSettingId,
        'FeesRuleDataId': value.feesRuleDataId,
        'AccountingCurrency': CurrenciesToJSON(value.accountingCurrency),
        'FeesRuleData': FeesRuleDatasToJSON(value.feesRuleData),
        'FundingRuleScpSetting': FundingRuleDataScpProviderSettingToJSON(value.fundingRuleScpSetting),
        'InstallmentPlans': value.installmentPlans === undefined ? undefined : ((value.installmentPlans as Array<any>).map(InstallmentPlansToJSON)),
    };
}


