/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InstallmentPlanEventSubscriberRecords,
    InstallmentPlanEventSubscriberRecordsFromJSON,
    InstallmentPlanEventSubscriberRecordsFromJSONTyped,
    InstallmentPlanEventSubscriberRecordsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InstallmentPlanEventSubscriberRecordSendLogsAllOf
 */
export interface InstallmentPlanEventSubscriberRecordSendLogsAllOf {
    /**
     * 
     * @type {number}
     * @memberof InstallmentPlanEventSubscriberRecordSendLogsAllOf
     */
    installmentPlanEventSubscriberRecordId: number;
    /**
     * 
     * @type {Date}
     * @memberof InstallmentPlanEventSubscriberRecordSendLogsAllOf
     */
    sendTime: Date;
    /**
     * 
     * @type {string}
     * @memberof InstallmentPlanEventSubscriberRecordSendLogsAllOf
     */
    response?: string;
    /**
     * 
     * @type {InstallmentPlanEventSubscriberRecords}
     * @memberof InstallmentPlanEventSubscriberRecordSendLogsAllOf
     */
    installmentPlanEventSubscriberRecord?: InstallmentPlanEventSubscriberRecords;
}

export function InstallmentPlanEventSubscriberRecordSendLogsAllOfFromJSON(json: any): InstallmentPlanEventSubscriberRecordSendLogsAllOf {
    return InstallmentPlanEventSubscriberRecordSendLogsAllOfFromJSONTyped(json, false);
}

export function InstallmentPlanEventSubscriberRecordSendLogsAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallmentPlanEventSubscriberRecordSendLogsAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'installmentPlanEventSubscriberRecordId': json['InstallmentPlanEventSubscriberRecordId'],
        'sendTime': (new Date(json['SendTime'])),
        'response': !exists(json, 'Response') ? undefined : json['Response'],
        'installmentPlanEventSubscriberRecord': !exists(json, 'InstallmentPlanEventSubscriberRecord') ? undefined : InstallmentPlanEventSubscriberRecordsFromJSON(json['InstallmentPlanEventSubscriberRecord']),
    };
}

export function InstallmentPlanEventSubscriberRecordSendLogsAllOfToJSON(value?: InstallmentPlanEventSubscriberRecordSendLogsAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'InstallmentPlanEventSubscriberRecordId': value.installmentPlanEventSubscriberRecordId,
        'SendTime': (value.sendTime.toISOString()),
        'Response': value.response,
        'InstallmentPlanEventSubscriberRecord': InstallmentPlanEventSubscriberRecordsToJSON(value.installmentPlanEventSubscriberRecord),
    };
}


