/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OperationType {
    None = 'None',
    Authorize = 'Authorize',
    Capture = 'Capture',
    Void = 'Void',
    Refund = 'Refund',
    Cancel = 'Cancel',
    CheckCaptureAsyncResponse = 'CheckCaptureAsyncResponse',
    VerifyCard = 'VerifyCard'
}

export function OperationTypeFromJSON(json: any): OperationType {
    return OperationTypeFromJSONTyped(json, false);
}

export function OperationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationType {
    return json as OperationType;
}

export function OperationTypeToJSON(value?: OperationType | null): any {
    return value as any;
}

