/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PisMembers,
    PisMembersFromJSON,
    PisMembersFromJSONTyped,
    PisMembersToJSON,
} from './';

/**
 * 
 * @export
 * @interface PisMemberPasswordHistoriesAllOf
 */
export interface PisMemberPasswordHistoriesAllOf {
    /**
     * 
     * @type {number}
     * @memberof PisMemberPasswordHistoriesAllOf
     */
    pisMemberId: number;
    /**
     * 
     * @type {PisMembers}
     * @memberof PisMemberPasswordHistoriesAllOf
     */
    pisMember?: PisMembers;
}

export function PisMemberPasswordHistoriesAllOfFromJSON(json: any): PisMemberPasswordHistoriesAllOf {
    return PisMemberPasswordHistoriesAllOfFromJSONTyped(json, false);
}

export function PisMemberPasswordHistoriesAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PisMemberPasswordHistoriesAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pisMemberId': json['PisMemberId'],
        'pisMember': !exists(json, 'PisMember') ? undefined : PisMembersFromJSON(json['PisMember']),
    };
}

export function PisMemberPasswordHistoriesAllOfToJSON(value?: PisMemberPasswordHistoriesAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PisMemberId': value.pisMemberId,
        'PisMember': PisMembersToJSON(value.pisMember),
    };
}


