/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicativeUserPasswordHistory,
    ApplicativeUserPasswordHistoryFromJSON,
    ApplicativeUserPasswordHistoryFromJSONTyped,
    ApplicativeUserPasswordHistoryToJSON,
    PisUserPasswordHistoriesAllOf,
    PisUserPasswordHistoriesAllOfFromJSON,
    PisUserPasswordHistoriesAllOfFromJSONTyped,
    PisUserPasswordHistoriesAllOfToJSON,
    PisUsers,
    PisUsersFromJSON,
    PisUsersFromJSONTyped,
    PisUsersToJSON,
} from './';

/**
 * 
 * @export
 * @interface PisUserPasswordHistories
 */
export interface PisUserPasswordHistories {
    /**
     * 
     * @type {number}
     * @memberof PisUserPasswordHistories
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PisUserPasswordHistories
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUserPasswordHistories
     */
    passwordHash?: string;
    /**
     * 
     * @type {Date}
     * @memberof PisUserPasswordHistories
     */
    passwordExpDate: Date;
    /**
     * 
     * @type {number}
     * @memberof PisUserPasswordHistories
     */
    pisUserId: number;
    /**
     * 
     * @type {PisUsers}
     * @memberof PisUserPasswordHistories
     */
    pisUser?: PisUsers;
}

export function PisUserPasswordHistoriesFromJSON(json: any): PisUserPasswordHistories {
    return PisUserPasswordHistoriesFromJSONTyped(json, false);
}

export function PisUserPasswordHistoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PisUserPasswordHistories {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['Id'],
        'password': !exists(json, 'Password') ? undefined : json['Password'],
        'passwordHash': !exists(json, 'PasswordHash') ? undefined : json['PasswordHash'],
        'passwordExpDate': (new Date(json['PasswordExpDate'])),
        'pisUserId': json['PisUserId'],
        'pisUser': !exists(json, 'PisUser') ? undefined : PisUsersFromJSON(json['PisUser']),
    };
}

export function PisUserPasswordHistoriesToJSON(value?: PisUserPasswordHistories | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Password': value.password,
        'PasswordHash': value.passwordHash,
        'PasswordExpDate': (value.passwordExpDate.toISOString()),
        'PisUserId': value.pisUserId,
        'PisUser': PisUsersToJSON(value.pisUser),
    };
}


