/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Agents,
    AgentsFromJSON,
    AgentsFromJSONTyped,
    AgentsToJSON,
    IUserPasswordHistory,
    IUserPasswordHistoryFromJSON,
    IUserPasswordHistoryFromJSONTyped,
    IUserPasswordHistoryToJSON,
    PisUserBusinessUnits,
    PisUserBusinessUnitsFromJSON,
    PisUserBusinessUnitsFromJSONTyped,
    PisUserBusinessUnitsToJSON,
    PisUserPasswordHistories,
    PisUserPasswordHistoriesFromJSON,
    PisUserPasswordHistoriesFromJSONTyped,
    PisUserPasswordHistoriesToJSON,
    PisUsersAllOf,
    PisUsersAllOfFromJSON,
    PisUsersAllOfFromJSONTyped,
    PisUsersAllOfToJSON,
    Roles,
    RolesFromJSON,
    RolesFromJSONTyped,
    RolesToJSON,
    UserJobSubscriptions,
    UserJobSubscriptionsFromJSON,
    UserJobSubscriptionsFromJSONTyped,
    UserJobSubscriptionsToJSON,
    UserPermissionLevel,
    UserPermissionLevelFromJSON,
    UserPermissionLevelFromJSONTyped,
    UserPermissionLevelToJSON,
    UserStatus,
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserWithActionItem,
    UserWithActionItemFromJSON,
    UserWithActionItemFromJSONTyped,
    UserWithActionItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface PisUsers
 */
export interface PisUsers {
    /**
     * 
     * @type {number}
     * @memberof PisUsers
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    culture?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    userFullName?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    phoneNumber?: string;
    /**
     * 
     * @type {Roles}
     * @memberof PisUsers
     */
    role?: Roles;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    uniqueId?: string;
    /**
     * 
     * @type {number}
     * @memberof PisUsers
     */
    loginAttempt: number;
    /**
     * 
     * @type {number}
     * @memberof PisUsers
     */
    maxInvalidLoginAttempts: number;
    /**
     * 
     * @type {UserStatus}
     * @memberof PisUsers
     */
    status: UserStatus;
    /**
     * 
     * @type {boolean}
     * @memberof PisUsers
     */
    isLocked: boolean;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    cultureName?: string;
    /**
     * 
     * @type {number}
     * @memberof PisUsers
     */
    roleId: number;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    loginUserName?: string;
    /**
     * 
     * @type {Date}
     * @memberof PisUsers
     */
    lastTimeLogin: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PisUsers
     */
    isDataPrivateRestricted: boolean;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    jobTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    faxNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    mobileNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    workPhoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    notes?: string;
    /**
     * 
     * @type {UserPermissionLevel}
     * @memberof PisUsers
     */
    type: UserPermissionLevel;
    /**
     * 
     * @type {string}
     * @memberof PisUsers
     */
    crmId?: string;
    /**
     * 
     * @type {Array<Agents>}
     * @memberof PisUsers
     */
    agents?: Array<Agents>;
    /**
     * 
     * @type {Array<PisUserBusinessUnits>}
     * @memberof PisUsers
     */
    pisUserBusinessUnits?: Array<PisUserBusinessUnits>;
    /**
     * 
     * @type {Array<PisUserPasswordHistories>}
     * @memberof PisUsers
     */
    pisUserPasswordHistories?: Array<PisUserPasswordHistories>;
    /**
     * 
     * @type {Array<UserJobSubscriptions>}
     * @memberof PisUsers
     */
    userJobSubscriptions?: Array<UserJobSubscriptions>;
    /**
     * 
     * @type {IUserPasswordHistory}
     * @memberof PisUsers
     */
    password?: IUserPasswordHistory;
}

export function PisUsersFromJSON(json: any): PisUsers {
    return PisUsersFromJSONTyped(json, false);
}

export function PisUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PisUsers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['Id'],
        'culture': !exists(json, 'Culture') ? undefined : json['Culture'],
        'userFullName': !exists(json, 'UserFullName') ? undefined : json['UserFullName'],
        'phoneNumber': !exists(json, 'PhoneNumber') ? undefined : json['PhoneNumber'],
        'role': !exists(json, 'Role') ? undefined : RolesFromJSON(json['Role']),
        'userName': !exists(json, 'UserName') ? undefined : json['UserName'],
        'uniqueId': !exists(json, 'UniqueId') ? undefined : json['UniqueId'],
        'loginAttempt': json['LoginAttempt'],
        'maxInvalidLoginAttempts': json['MaxInvalidLoginAttempts'],
        'status': UserStatusFromJSON(json['Status']),
        'isLocked': json['IsLocked'],
        'email': !exists(json, 'Email') ? undefined : json['Email'],
        'cultureName': !exists(json, 'CultureName') ? undefined : json['CultureName'],
        'roleId': json['RoleId'],
        'loginUserName': !exists(json, 'LoginUserName') ? undefined : json['LoginUserName'],
        'lastTimeLogin': (new Date(json['LastTimeLogin'])),
        'isDataPrivateRestricted': json['IsDataPrivateRestricted'],
        'firstName': !exists(json, 'FirstName') ? undefined : json['FirstName'],
        'lastName': !exists(json, 'LastName') ? undefined : json['LastName'],
        'jobTitle': !exists(json, 'JobTitle') ? undefined : json['JobTitle'],
        'faxNumber': !exists(json, 'FaxNumber') ? undefined : json['FaxNumber'],
        'mobileNumber': !exists(json, 'MobileNumber') ? undefined : json['MobileNumber'],
        'workPhoneNumber': !exists(json, 'WorkPhoneNumber') ? undefined : json['WorkPhoneNumber'],
        'notes': !exists(json, 'Notes') ? undefined : json['Notes'],
        'type': UserPermissionLevelFromJSON(json['Type']),
        'crmId': !exists(json, 'CrmId') ? undefined : json['CrmId'],
        'agents': !exists(json, 'Agents') ? undefined : ((json['Agents'] as Array<any>).map(AgentsFromJSON)),
        'pisUserBusinessUnits': !exists(json, 'PisUserBusinessUnits') ? undefined : ((json['PisUserBusinessUnits'] as Array<any>).map(PisUserBusinessUnitsFromJSON)),
        'pisUserPasswordHistories': !exists(json, 'PisUserPasswordHistories') ? undefined : ((json['PisUserPasswordHistories'] as Array<any>).map(PisUserPasswordHistoriesFromJSON)),
        'userJobSubscriptions': !exists(json, 'UserJobSubscriptions') ? undefined : ((json['UserJobSubscriptions'] as Array<any>).map(UserJobSubscriptionsFromJSON)),
        'password': !exists(json, 'Password') ? undefined : IUserPasswordHistoryFromJSON(json['Password']),
    };
}

export function PisUsersToJSON(value?: PisUsers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Culture': value.culture,
        'UserFullName': value.userFullName,
        'PhoneNumber': value.phoneNumber,
        'Role': RolesToJSON(value.role),
        'UserName': value.userName,
        'UniqueId': value.uniqueId,
        'LoginAttempt': value.loginAttempt,
        'MaxInvalidLoginAttempts': value.maxInvalidLoginAttempts,
        'Status': UserStatusToJSON(value.status),
        'IsLocked': value.isLocked,
        'Email': value.email,
        'CultureName': value.cultureName,
        'RoleId': value.roleId,
        'LoginUserName': value.loginUserName,
        'LastTimeLogin': (value.lastTimeLogin.toISOString()),
        'IsDataPrivateRestricted': value.isDataPrivateRestricted,
        'FirstName': value.firstName,
        'LastName': value.lastName,
        'JobTitle': value.jobTitle,
        'FaxNumber': value.faxNumber,
        'MobileNumber': value.mobileNumber,
        'WorkPhoneNumber': value.workPhoneNumber,
        'Notes': value.notes,
        'Type': UserPermissionLevelToJSON(value.type),
        'CrmId': value.crmId,
        'Agents': value.agents === undefined ? undefined : ((value.agents as Array<any>).map(AgentsToJSON)),
        'PisUserBusinessUnits': value.pisUserBusinessUnits === undefined ? undefined : ((value.pisUserBusinessUnits as Array<any>).map(PisUserBusinessUnitsToJSON)),
        'PisUserPasswordHistories': value.pisUserPasswordHistories === undefined ? undefined : ((value.pisUserPasswordHistories as Array<any>).map(PisUserPasswordHistoriesToJSON)),
        'UserJobSubscriptions': value.userJobSubscriptions === undefined ? undefined : ((value.userJobSubscriptions as Array<any>).map(UserJobSubscriptionsToJSON)),
        'Password': IUserPasswordHistoryToJSON(value.password),
    };
}


