/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProcessorType {
    None = 'None',
    PayVision = 'PayVision',
    NAB = 'NAB',
    AuthNet = 'AuthNet',
    Jetpay = 'Jetpay',
    FirstData = 'FirstData',
    CardConnect = 'CardConnect',
    PaymentManager = 'PaymentManager'
}

export function ProcessorTypeFromJSON(json: any): ProcessorType {
    return ProcessorTypeFromJSONTyped(json, false);
}

export function ProcessorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessorType {
    return json as ProcessorType;
}

export function ProcessorTypeToJSON(value?: ProcessorType | null): any {
    return value as any;
}

