/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    LogoutResponse,
    LogoutResponseFromJSON,
    LogoutResponseToJSON,
} from '../models';

export interface LogoutPostRequest {
    request: object;
}

/**
 * no description
 */
export class LogoutApi extends runtime.BaseAPI {

    /**
     */
    async logoutPostRaw(requestParameters: LogoutPostRequest): Promise<runtime.ApiResponse<LogoutResponse>> {
        if (requestParameters.request === null || requestParameters.request === undefined) {
            throw new runtime.RequiredError('request','Required parameter requestParameters.request was null or undefined when calling logoutPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        const response = await this.request({
            path: `/api/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.request as any,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => LogoutResponseFromJSON(jsonValue));
    }

    /**
     */
    async logoutPost(requestParameters: LogoutPostRequest): Promise<LogoutResponse> {
        const response = await this.logoutPostRaw(requestParameters);
        return await response.value();
    }

}
